FROM node:24-alpine

# Enable corepack
RUN corepack enable

WORKDIR /app

# Copy package.json and pnpm-lock.yaml to the working directory
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Install dependencies using pnpm with frozen lockfile to ensure consistent installs
RUN pnpm install --frozen-lockfile

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the application will run on
EXPOSE 3001

# Start the application using pnpm
CMD ["pnpm", "start:dev"]
